"""Demo provider — realistic international tenders for Ukrainian heating/water infra.

These represent the kind of tenders actually published by international donors
for Ukraine and neighbouring countries. Replace with live scraping/API per donor.
"""
from __future__ import annotations
from typing import Optional
from ..base import TenderProvider, UniversalTenderResult
from ..scoring import score_tender, matches_query

_TENDERS: list[dict] = [
    # ── NEFCO ────────────────────────────────────────────────────────────────
    {
        "id": "nefco-ua-2025-001",
        "source": "NEFCO",
        "title": "Modernisation of District Heating Network in Lviv — Heat Exchanger Replacement",
        "status": "active",
        "amount": 3_200_000,
        "currency": "EUR",
        "deadline": "2025-08-31",
        "published_at": "2025-05-10",
        "procuring_entity": "Lvivteploenergo",
        "country": "Ukraine",
        "region": "Lviv Oblast",
        "city": "Lviv",
        "donor": "NEFCO",
        "sector": "District Heating",
        "cpv_codes": ["45232140", "42511110"],
        "source_url": "https://www.nefco.int/financing/",
    },
    {
        "id": "nefco-ua-2025-002",
        "source": "NEFCO",
        "title": "Supply and Installation of Heat Substations (ITP) — Kyiv Residential District",
        "status": "active",
        "amount": 1_800_000,
        "currency": "EUR",
        "deadline": "2025-09-15",
        "published_at": "2025-04-22",
        "procuring_entity": "Kyivenergo",
        "country": "Ukraine",
        "region": "Kyiv",
        "city": "Kyiv",
        "donor": "NEFCO",
        "sector": "Heat Substations",
        "cpv_codes": ["42511000", "45331100"],
        "source_url": "https://www.nefco.int/financing/",
    },
    # ── GIZ ──────────────────────────────────────────────────────────────────
    {
        "id": "giz-ua-2025-001",
        "source": "GIZ",
        "title": "Energy Efficiency in Municipal District Heating — Pumping Equipment Procurement",
        "status": "active",
        "amount": 950_000,
        "currency": "EUR",
        "deadline": "2025-07-30",
        "published_at": "2025-04-05",
        "procuring_entity": "GIZ Ukraine",
        "country": "Ukraine",
        "region": "Dnipropetrovsk Oblast",
        "city": "Dnipro",
        "donor": "GIZ",
        "sector": "Energy Efficiency",
        "cpv_codes": ["42122000", "45331110"],
        "source_url": "https://www.giz.de/en/worldwide/ukraine.html",
    },
    {
        "id": "giz-md-2025-001",
        "source": "GIZ",
        "title": "Rehabilitation of Water Supply and Sanitation Infrastructure in Moldova",
        "status": "active",
        "amount": 2_100_000,
        "currency": "EUR",
        "deadline": "2025-10-01",
        "published_at": "2025-05-01",
        "procuring_entity": "GIZ Moldova",
        "country": "Moldova",
        "region": "Chisinau",
        "city": "Chisinau",
        "donor": "GIZ",
        "sector": "Water Supply",
        "cpv_codes": ["45232150", "65111000"],
        "source_url": "https://www.giz.de/en/worldwide/moldova.html",
    },
    # ── EBRD ─────────────────────────────────────────────────────────────────
    {
        "id": "ebrd-ua-2025-001",
        "source": "EBRD",
        "title": "Kharkiv District Heating Rehabilitation — Boiler Houses and Heat Distribution",
        "status": "active",
        "amount": 15_000_000,
        "currency": "EUR",
        "deadline": "2025-11-30",
        "published_at": "2025-03-15",
        "procuring_entity": "Kharkivteplopostachannia",
        "country": "Ukraine",
        "region": "Kharkiv Oblast",
        "city": "Kharkiv",
        "donor": "EBRD",
        "sector": "District Heating",
        "cpv_codes": ["45232140", "44621100", "45331000"],
        "source_url": "https://ecepp.ebrd.com/",
    },
    {
        "id": "ebrd-ua-2025-002",
        "source": "EBRD",
        "title": "Odesa Water Utility — Pumping Stations Upgrade and Pipe Replacement",
        "status": "active",
        "amount": 8_500_000,
        "currency": "USD",
        "deadline": "2025-09-30",
        "published_at": "2025-04-01",
        "procuring_entity": "KP Odesmiskvodokanal",
        "country": "Ukraine",
        "region": "Odesa Oblast",
        "city": "Odesa",
        "donor": "EBRD",
        "sector": "Water Supply",
        "cpv_codes": ["42122000", "45232150"],
        "source_url": "https://ecepp.ebrd.com/",
    },
    # ── World Bank (supplementing live API) ──────────────────────────────────
    {
        "id": "wb-ua-2025-001",
        "source": "World Bank",
        "title": "Ukraine District Heating Efficiency Project — ITP Automation Systems",
        "status": "active",
        "amount": 50_000_000,
        "currency": "USD",
        "deadline": "2025-12-31",
        "published_at": "2025-02-20",
        "procuring_entity": "Ministry of Communities and Territories of Ukraine",
        "country": "Ukraine",
        "region": "Multiple Regions",
        "city": "Kyiv",
        "donor": "World Bank",
        "sector": "District Heating",
        "cpv_codes": ["42511000", "45331100", "42512000"],
        "source_url": "https://projects.worldbank.org/",
    },
    # ── USAID ─────────────────────────────────────────────────────────────────
    {
        "id": "usaid-ua-2025-001",
        "source": "USAID",
        "title": "Municipal Energy Resilience — Emergency Heating Infrastructure Repair",
        "status": "active",
        "amount": 4_200_000,
        "currency": "USD",
        "deadline": "2025-08-01",
        "published_at": "2025-05-05",
        "procuring_entity": "USAID Ukraine Mission",
        "country": "Ukraine",
        "region": "Multiple Regions",
        "city": "Kyiv",
        "donor": "USAID",
        "sector": "Energy Resilience",
        "cpv_codes": ["45331000", "44621100"],
        "source_url": "https://www.usaid.gov/ukraine",
    },
    {
        "id": "usaid-ua-2025-002",
        "source": "USAID",
        "title": "Decentralized Water Systems — Pumping Station Rehabilitation in Eastern Ukraine",
        "status": "active",
        "amount": 2_700_000,
        "currency": "USD",
        "deadline": "2025-07-15",
        "published_at": "2025-04-10",
        "procuring_entity": "USAID Water Security Project",
        "country": "Ukraine",
        "region": "Donetsk Oblast",
        "city": "Kramatorsk",
        "donor": "USAID",
        "sector": "Water Supply",
        "cpv_codes": ["42122000", "45232151"],
        "source_url": "https://www.usaid.gov/ukraine",
    },
    # ── UNDP ──────────────────────────────────────────────────────────────────
    {
        "id": "undp-ua-2025-001",
        "source": "UNDP",
        "title": "Restoration of Heating Systems in War-Affected Communities — Thermal Substations",
        "status": "active",
        "amount": 3_600_000,
        "currency": "USD",
        "deadline": "2025-06-30",
        "published_at": "2025-03-01",
        "procuring_entity": "UNDP Ukraine",
        "country": "Ukraine",
        "region": "Mykolaiv Oblast",
        "city": "Mykolaiv",
        "donor": "UNDP",
        "sector": "Heat Substations",
        "cpv_codes": ["42511000", "45331100"],
        "source_url": "https://procurement-notices.undp.org/",
    },
    # ── EIB ───────────────────────────────────────────────────────────────────
    {
        "id": "eib-ua-2025-001",
        "source": "EIB",
        "title": "Urban Water Infrastructure Modernisation — Heat Exchangers and Control Systems",
        "status": "active",
        "amount": 12_000_000,
        "currency": "EUR",
        "deadline": "2025-10-15",
        "published_at": "2025-02-28",
        "procuring_entity": "EIB Technical Assistance Ukraine",
        "country": "Ukraine",
        "region": "Poltava Oblast",
        "city": "Poltava",
        "donor": "EIB",
        "sector": "Water & Heating",
        "cpv_codes": ["42511110", "45232140"],
        "source_url": "https://www.eib.org/en/about/procurement/index.htm",
    },
    # ── KfW ───────────────────────────────────────────────────────────────────
    {
        "id": "kfw-ua-2025-001",
        "source": "KfW",
        "title": "Reconstruction of Heat Networks — Pipe Insulation and Pumping Stations",
        "status": "active",
        "amount": 7_500_000,
        "currency": "EUR",
        "deadline": "2025-09-01",
        "published_at": "2025-04-15",
        "procuring_entity": "KfW Development Bank / Ministry of Finance of Ukraine",
        "country": "Ukraine",
        "region": "Zaporizhzhia Oblast",
        "city": "Zaporizhzhia",
        "donor": "KfW",
        "sector": "District Heating",
        "cpv_codes": ["45232140", "42122000", "44163110"],
        "source_url": "https://www.kfw-entwicklungsbank.de/International-financing/KfW-Development-Bank/",
    },
    # ── UNICEF ────────────────────────────────────────────────────────────────
    {
        "id": "unicef-ua-2025-001",
        "source": "UNICEF",
        "title": "Winterisation — Heating Equipment for Schools and Kindergartens",
        "status": "active",
        "amount": 1_200_000,
        "currency": "USD",
        "deadline": "2025-07-01",
        "published_at": "2025-05-12",
        "procuring_entity": "UNICEF Ukraine",
        "country": "Ukraine",
        "region": "Multiple Regions",
        "city": "Kyiv",
        "donor": "UNICEF",
        "sector": "Heating Equipment",
        "cpv_codes": ["39715200", "42511000"],
        "source_url": "https://supply.unicef.org/",
    },
    # ── UNOPS ─────────────────────────────────────────────────────────────────
    {
        "id": "unops-ua-2025-001",
        "source": "UNOPS",
        "title": "Supply of Water Pumping Equipment for Vodokanal Utilities",
        "status": "active",
        "amount": 890_000,
        "currency": "USD",
        "deadline": "2025-06-20",
        "published_at": "2025-05-01",
        "procuring_entity": "UNOPS Ukraine Operations Centre",
        "country": "Ukraine",
        "region": "Kherson Oblast",
        "city": "Kherson",
        "donor": "UNOPS",
        "sector": "Water Supply",
        "cpv_codes": ["42122000", "65111000"],
        "source_url": "https://www.ungm.org/",
    },
    # ── Nordic Environment Finance Corporation ────────────────────────────────
    {
        "id": "nefco-ge-2025-001",
        "source": "NEFCO",
        "title": "Tbilisi District Heating Pilot — Heat Substation Automation",
        "status": "active",
        "amount": 700_000,
        "currency": "EUR",
        "deadline": "2025-08-15",
        "published_at": "2025-04-30",
        "procuring_entity": "Tbilisi Energy",
        "country": "Georgia",
        "region": "Tbilisi",
        "city": "Tbilisi",
        "donor": "NEFCO",
        "sector": "District Heating",
        "cpv_codes": ["42511000"],
        "source_url": "https://www.nefco.int/financing/",
    },
    # ── AFD ───────────────────────────────────────────────────────────────────
    {
        "id": "afd-ua-2025-001",
        "source": "AFD",
        "title": "Urban Water and Sanitation Improvement — Pumping Stations and Networks",
        "status": "active",
        "amount": 5_000_000,
        "currency": "EUR",
        "deadline": "2025-11-01",
        "published_at": "2025-03-20",
        "procuring_entity": "Agence Française de Développement Ukraine",
        "country": "Ukraine",
        "region": "Vinnytsia Oblast",
        "city": "Vinnytsia",
        "donor": "AFD",
        "sector": "Water & Sanitation",
        "cpv_codes": ["42122000", "45232151", "65111000"],
        "source_url": "https://www.afd.fr/en/",
    },
    # ── EU / European Commission ──────────────────────────────────────────────
    {
        "id": "eu-ua-2025-001",
        "source": "European Commission",
        "title": "EU4Energy — Energy Efficiency Investments in Municipal Heating (Call for Proposals)",
        "status": "active",
        "amount": 20_000_000,
        "currency": "EUR",
        "deadline": "2025-10-31",
        "published_at": "2025-01-15",
        "procuring_entity": "European Commission DG NEAR",
        "country": "Ukraine",
        "region": "Multiple Regions",
        "city": "Brussels / Kyiv",
        "donor": "European Commission",
        "sector": "Energy Efficiency",
        "cpv_codes": ["45331000", "45232140"],
        "source_url": "https://ec.europa.eu/info/funding-tenders/find-funding_en",
    },
    # ── IFC ───────────────────────────────────────────────────────────────────
    {
        "id": "ifc-ua-2025-001",
        "source": "IFC",
        "title": "ESCO Financing for Energy-Efficient Heating Upgrades in Multi-Family Buildings",
        "status": "active",
        "amount": 6_000_000,
        "currency": "USD",
        "deadline": "2025-12-01",
        "published_at": "2025-02-01",
        "procuring_entity": "IFC Ukraine Advisory",
        "country": "Ukraine",
        "region": "Kyiv",
        "city": "Kyiv",
        "donor": "IFC",
        "sector": "Energy Efficiency",
        "cpv_codes": ["42511000", "45331100"],
        "source_url": "https://www.ifc.org/",
    },
]


class DemoProvider(TenderProvider):
    id = "demo"
    label = "Demo (NEFCO, GIZ, EBRD, USAID, UNDP, EIB, KfW, UNICEF, UNOPS, AFD, EU, IFC)"

    async def search(
        self,
        q: Optional[str],
        filters: dict,
        limit: int,
    ) -> list[UniversalTenderResult]:
        results: list[UniversalTenderResult] = []

        for t in _TENDERS:
            search_text = f"{t['title']} {t.get('sector', '')} {t.get('donor', '')} {t.get('country', '')}"

            if q and not matches_query(search_text, q):
                continue

            priority, supply_match = score_tender(
                title=t["title"],
                amount=t.get("amount"),
                currency=t.get("currency", "USD"),
                country=t.get("country"),
                sector=t.get("sector"),
            )

            results.append(UniversalTenderResult(
                id=t["id"],
                source=t["source"],
                title=t["title"],
                status=t.get("status", "active"),
                amount=t.get("amount"),
                currency=t.get("currency", "USD"),
                deadline=t.get("deadline"),
                published_at=t.get("published_at"),
                procuring_entity=t.get("procuring_entity"),
                city=t.get("city"),
                country=t.get("country"),
                region=t.get("region"),
                donor=t.get("donor"),
                sector=t.get("sector"),
                cpv_codes=t.get("cpv_codes", []),
                source_url=t["source_url"],
                priority=priority,
                supply_match=supply_match,
            ))

        return results[:limit]
